<#assign attrJavaPackage = project.getProjectModule().getAttributeValue( "java_package", "com.noname" ) >
<#assign objectName = object.getName() >
/**
 * This file is generated by the Amit
 * don't modify it manually
 */
package ${attrJavaPackage};

import com.fasterxml.jackson.core.JsonParser;
import java.io.IOException;
import com.amitapi.json.runtime.*;

public enum ${objectName} implements JsonSerializableEnum {
	
<#list object.getValues() as value >
	<#assign name = value.getName()?upper_case >
	${name}( <#if value.getIntegerValue()??>${value.getIntegerValue()}<#else>"${value.getStringValue()?replace("\"", "\\\"")}"</#if> )<#if value_has_next>,<#else>;</#if>
</#list>
	
	private String stringValue;
	private Integer intValue;
	
	${objectName}( int intValue ) {
		this.intValue = intValue;
		this.stringValue = Integer.toString( intValue );
	}

	${objectName}( String stringValue ) {
		this.stringValue = stringValue;
		try {
			this.intValue = Integer.valueOf( stringValue );
		} catch( NumberFormatException e ) {
		}
	}
	
	public String getStringValue() {
		return stringValue;
	}
	
	public Integer getIntegerValue() {
		return intValue;
	}
	
	protected static ${objectName} deserialize( JsonParser jp ) throws IOException {
		String stringValue = jp.getText();
		Integer intNumber = null;
		
		try {
			intNumber = Integer.valueOf( stringValue );
		} catch( NumberFormatException e ) {
		}
		
		for( ${objectName} value : values() ) {
			if( intNumber != null && value.intValue != null ) {
				if( intNumber.equals( value.intValue ) ) {
					return value;
				}
			} else {
				if( stringValue.equals( value.stringValue ) ) {
					return value;
				}
			}
		}
		
		throw new IllegalArgumentException( String.format( "Unknown enum value '%s'", stringValue ) );
	}
}