<#import "macros.ftl" as my>
<#assign attrJavaPackageModel = project.getProjectModule().getAttributeValue( "java_package", "com.noname" ) >
<#assign attrJavaPackage = attrJavaPackageModel + ".call" >
<#assign objectName = object.getName() >
/**
 * This file is generated by the Amit
 * don't modify it manually
 */
package ${attrJavaPackage};

<#if object.dependsOnTypeArray() >
import java.util.List;
import java.util.ArrayList;
</#if>
<#if object.dependsOnType( "datetime" ) >
import java.time.LocalDateTime;
</#if>
<#if object.dependsOnType( "uuid" ) >
import java.util.UUID;
</#if>

import java.io.IOException;
import java.util.Objects;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.amitapi.json.runtime.*;
import ${attrJavaPackageModel}.*;
/**
 * interface ${objectName} call data
 */
public final class Call${objectName} {

<#list object.getFunctions() as function >
<#assign fname = function.getName() >
<#assign ARfname = amit.AUpper( fname ) + "Request"  >
<#assign APfname = amit.AUpper( fname ) + "Responce"  >
		
/**
 * function ${fname} Request
 */
public static final class ${ARfname} implements JsonSerializable {
<@my.classMembers items=function.getArguments() />
<@my.classGettersSetters items=function.getArguments() className=ARfname />

<@my.hashCodeFunction items=function.getArguments() hasBaseType=false />

<@my.equalsFunction items=function.getArguments() className=ARfname hasBaseType=false />

<@my.toStringFunction items=function.getArguments() className=ARfname hasBaseType=false />

<@my.serializeFuctions className=ARfname hasBaseType=false />

<@my.serializeMembersFunction items=function.getArguments() hasBaseType=false />

<@my.parseTokenFunction items=function.getArguments() hasBaseType=false />

<@my.classFactory name=ARfname />	
}		

/**
 * function ${fname} Responce
 */
public static final class ${APfname} {

}

</#list>

}