<#import "macros.ftl" as my>
<#assign attrJavaPackage = project.getProjectModule().getAttributeValue( "java_package", "com.noname" ) >
/**
 * This file is generated by the Amit
 * don't modify it manually
 */
package ${attrJavaPackage};

import java.util.Objects;
<#if object.dependsOnTypeArray() >
import java.util.List;
</#if>
<#if object.dependsOnType( "datetime" ) >
import java.time.LocalDateTime;
</#if>
<#if object.dependsOnType( "uuid" ) >
import java.util.UUID;
</#if>

import java.io.IOException;
import com.fasterxml.jackson.core.JsonGenerator;

/**
 * type ${object.getName()}
 */
public class ${object.getName()} {
<#list object.getMembers() as member >
	private ${my.javaType( member ) } ${member.getName()};
</#list>	

<#list object.getMembers() as member >
	<#assign type = my.javaType( member ) >
	<#assign name = member.getName() >	
	<#assign Aname = amit.AUpper( member.getName() ) >	
	public ${type} get${Aname}() {
		return ${name};
	}
	public void set${Aname}( ${type} ${name} ) {
		this.${name} = ${name};
	}

</#list>
	@Override
	public int hashCode() {
		return Objects.hash(
<#list object.getMembers() as member >
			${member.getName()}<#if member_has_next>,</#if>
</#list>	
		);
	}

	@Override
	public boolean equals( Object obj ) {
		if( obj == null ) {
			return false;
		}

		if( getClass() != obj.getClass() ) {
			return false;
		}

		${object.getName()} other = (${object.getName()}) obj;

		return 
<#list object.getMembers() as member >
			Objects.equals( this.${member.getName()}, other.${member.getName()} ) <#if member_has_next>&&</#if>
</#list>	
			;
	}

	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append( "${object.getName()} [" );
<#list object.getMembers() as member >
		
		sb.append( "${member.getName()}" );
		sb.append( "=" );
		sb.append( ${member.getName()} );
		<#if member_has_next>sb.append( "," );</#if>
</#list>
		sb.append( "]" );
		return sb.toString();
	}
	
	public void serialize( JsonGenerator j ) throws IOException {
		j.writeStartObject();
<#list object.getMembers() as member >
		
		if( ${member.getName()} != null ) {
			j.writeFieldName( "${member.getName()}" );
	<#if member.isArray() >
			j.writeStartArray();
			for( ${my.javaTypeNoArray( member )} obj : ${member.getName()} ) {
		<#switch member.getTypeName()>
		<#case "boolean">
				j.writeBoolean( obj );
		<#break>
		<#case "int">
				j.writeNumber( obj );
		<#break>
		<#case "string">
				j.writeString( obj );
		<#break>
		<#case "long">
				j.writeNumber( obj );
		<#break>
		<#case "double">
				j.writeNumber( obj );
		<#break>
		<#case "uuid">
				j.writeString( obj.toString() );
		<#break>
		<#case "datetime">
				j.writeString( obj.toString() );
		<#break>
		<#default>
				obj.serialize( j );
		</#switch>
			}
			j.writeEndArray();
	<#else>
		<#switch member.getTypeName()>
		<#case "boolean">
			j.writeBoolean( ${member.getName()} );
		<#break>
		<#case "int">
			j.writeNumber( ${member.getName()} );
		<#break>
		<#case "string">
			j.writeString( ${member.getName()} );
		<#break>
		<#case "long">
			j.writeNumber( ${member.getName()} );
		<#break>
		<#case "double">
			j.writeNumber( ${member.getName()} );
		<#break>
		<#case "uuid">
			j.writeString( ${member.getName()}.toString() );
		<#break>
		<#case "datetime">
			j.writeString( ${member.getName()}.toString() );
		<#break>
		<#default>
			${member.getName()}.serialize( j );
		</#switch>
	</#if>
		}
</#list>

		j.writeEndObject();
	}
	
	public static ${object.getName()} deserialize( JsonParser j ) throws IOException {
		if (j.nextToken() != JsonToken.START_OBJECT) {
			throw new IllegalArgumentException ( "Expected data to start with an Object" );
		}
		
		${object.getName()} result = new ${object.getName()}();
		
		while( j.nextToken() != JsonToken.END_OBJECT ) {
		
		}
		return result;
	}
}
