<#assign attrJavaPackage = project.getProjectModule().getAttributeValue( "java_package", "com.noname" ) >
<#assign objectName = object.getName() >
/**
 * This file is generated by the Amit
 * don't modify it manually
 */
package ${attrJavaPackage};

public enum ${objectName} implements com.amitapi.json.runtime.__JsonSerializableEnum {
	
<#list object.getValues() as value >
	<#assign name = value.getName()?upper_case >
	${name}( <#if value.getIntegerValue()??>${value.getIntegerValue()}<#else>"${value.getStringValue()?replace("\"", "\\\"")}"</#if> )<#if value_has_next>,<#else>;</#if>
</#list>
	
	private String stringValue;
	private Integer intValue;
	
	${objectName}( int intValue ) {
		this.intValue = intValue;
		this.stringValue = Integer.toString( intValue );
	}

	${objectName}( String stringValue ) {
		this.stringValue = stringValue;
		try {
			this.intValue = Integer.valueOf( stringValue );
		} catch( NumberFormatException e ) {
		}
	}
	
	/**
	 * !!! for internal use only
	 */
	public String __getStringValue() {
		return stringValue;
	}
	
	/**
	 * !!! for internal use only
	 */
	public Integer __getIntegerValue() {
		return intValue;
	}
}